- name: Update Proxmox
  hosts: proxmox
  become: no
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: yes
- name: Update Linux Systems
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: yes