- name: Update Proxmox
  hosts: proxmox
  become: false
  tasks:
    - name: Update/Upgrade Proxmox cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
- name: Update/Upgrade K3S Cluster
  hosts: k3s_cluster
  become: true
  tasks:
    - name: apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
