- name: Deploy Helm manifest files
  hosts: master
  become: true
  tasks:
    - name: Copy Helm Manifest file
      ansible.builtin.copy:
        src: k3s-nfs-storageclass.yaml
        dest: /var/lib/rancher/k3s/server/manifests/k3s-nfs-storageclass.yaml
        mode: '0755'
