- name: Deploy Helm manifest files
  hosts: master
  become: yes
  tasks:
    - name: Copy Helm Manifest file
      copy:
        src: k3s-nfs-storageclass.yaml
        dest: /var/lib/rancher/k3s/server/manifests/k3s-nfs-storageclass.yaml