- name: Install additonal Packages on K3S servers
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Install packages on K3S servers
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nfs-common