- name: Install additonal Packages on K3S servers
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Update cache
      ansible.builtin.apt_repository:
        update_cache: true
        upgrade: true
    - name: Install packages on K3S servers
      ansible.builtin.apt_repository:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nfs-common
